// Generates a release-PR title + description (and, for develop -> main, a
// semver bump judgement) from the set of PRs being promoted.
//
// Inputs (env):
//   ANTHROPIC_API_KEY  - required by the SDK client
//   BASE_BRANCH        - PR base branch (main | release)
//   HEAD_BRANCH        - PR head branch (develop | main)
//   INCLUDE_BUMP       - "true" to also judge the semver bump (develop -> main)
//   CURRENT_VERSION    - package.json version currently on the base branch
//   PR_DATA_FILE       - path to JSON array: [{number, title, body, author}]
//   COMMITS_FILE       - path to plain-text list of non-merge commit subjects
//
// Output: a single JSON object on stdout:
//   { title, description }                        when INCLUDE_BUMP != "true"
//   { title, description, bump, bump_reason }     when INCLUDE_BUMP == "true"

import fs from "node:fs";
import Anthropic from "@anthropic-ai/sdk";

const baseBranch = process.env.BASE_BRANCH;
const headBranch = process.env.HEAD_BRANCH;
const includeBump = process.env.INCLUDE_BUMP === "true";
const currentVersion = process.env.CURRENT_VERSION ?? "unknown";

const prs = JSON.parse(fs.readFileSync(process.env.PR_DATA_FILE, "utf8"));
const commits = fs.readFileSync(process.env.COMMITS_FILE, "utf8").trim();

const truncate = (s, n) =>
  s && s.length > n ? `${s.slice(0, n)}\n…[truncated]` : (s ?? "");

const prSections =
  prs.length > 0
    ? prs
        .map(
          (p) =>
            `### PR #${p.number}: ${p.title}\nAuthor: ${p.author}\n\n${
              truncate(p.body, 3000) || "(no description)"
            }`,
        )
        .join("\n\n---\n\n")
    : "(no PR metadata available — judge from the commit subjects below)";

const baseProperties = {
  title: {
    type: "string",
    description:
      'Pull request title, <= 72 characters, format: "Release: <summary of what this promotion ships>"',
  },
  description: {
    type: "string",
    description: "Pull request description in GitHub-flavored markdown",
  },
};

const schema = includeBump
  ? {
      type: "object",
      additionalProperties: false,
      required: ["title", "description", "bump", "bump_reason"],
      properties: {
        ...baseProperties,
        bump: { type: "string", enum: ["major", "minor", "patch"] },
        bump_reason: {
          type: "string",
          description: "One or two sentences justifying the chosen bump",
        },
      },
    }
  : {
      type: "object",
      additionalProperties: false,
      required: ["title", "description"],
      properties: baseProperties,
    };

const system = `You write promotion pull requests for web-skeleton, a React +
Next.js web application monorepo. A promotion PR merges everything on one
long-lived branch into the next one (develop -> main, or main -> release).
Your job is to read the feature PRs that were merged into the head branch
since the last promotion and summarize them for reviewers.

Rules for the description:
- Start with a "## Summary" section: a few bullets grouping the changes by
  theme (features, fixes, infra), written for a reviewer deciding whether to
  promote. Plain language, no hype.
- Then an "## Included PRs" section listing each PR as "- #<number> — <title>".
- Do not invent changes that are not evidenced by the PRs/commits provided.
- Do not include a sign-off, footer, or "generated by" note; the workflow
  appends its own.`;

const bumpInstructions = `
Also judge the semantic-version bump this promotion represents, relative to
version ${currentVersion} currently on ${baseBranch}:
- "major": any breaking change to an API contract, URL structure, or behavior
  that existing consumers depend on (including BREAKING CHANGE notes or "!"
  conventional-commit markers).
- "minor": at least one backwards-compatible new feature or capability.
- "patch": only fixes, refactors, chores, docs, tests, or CI changes.
Judge from the actual content of the PRs, not just the commit-type prefixes.
Add a "## Version" section to the description stating the chosen bump and the
one-line reason.`;

const prompt = `Promotion PR: ${headBranch} -> ${baseBranch}

Merged PRs being promoted:

${prSections}

Non-merge commit subjects in the range (fallback/context):

${commits || "(none)"}
${includeBump ? bumpInstructions : ""}`;

const client = new Anthropic();

try {
  const response = await client.messages.create({
    model: "claude-opus-5",
    max_tokens: 16000,
    thinking: { type: "adaptive" },
    output_config: { format: { type: "json_schema", schema } },
    system,
    messages: [{ role: "user", content: prompt }],
  });

  if (response.stop_reason === "refusal") {
    console.error("Anthropic API refused the request", response.stop_details);
    process.exit(1);
  }
  if (response.stop_reason === "max_tokens") {
    console.error(
      "Response truncated at max_tokens; output may be invalid JSON",
    );
    process.exit(1);
  }

  const text = response.content.find((b) => b.type === "text")?.text;
  if (!text) {
    console.error("No text block in response");
    process.exit(1);
  }

  // Re-serialize so downstream jq always gets canonical single-object JSON.
  process.stdout.write(JSON.stringify(JSON.parse(text)));
} catch (error) {
  if (error instanceof Anthropic.RateLimitError) {
    console.error("Anthropic API rate limited:", error.message);
  } else if (error instanceof Anthropic.APIError) {
    console.error(`Anthropic API error ${error.status}:`, error.message);
  } else {
    console.error(error);
  }
  process.exit(1);
}
